### ISSUE TITLE
Icon interact strangly with Picom compositor

### ISSUE THREAD

**Issue by propeeves** [neagix/idesk#5]
I'm running OpenBox and Picom (with nitrogen to change wallpapers) and was looking for a way to get icons on the desktop without running a completely different DE, so thank you for the software!

The only issue I'm currently having is that picom seems to be giving the icons transparency like any other window, and the transparency goes right through the wallpaper. The icon was showing minimized windows (which I fixed by setting transparency to 0 in the config), but now the caption is also showing minimized windows in a box around it. This continues even after picom is closed, strangely enough.

I was wondering if there was a way in the config to modify the caption, or if you know what window class/name to use to exclude idesk entirely from picom.

Thank you for your time.

**Comment by neagix** [comment]
idesk uses X11 alpha transparency; what do you mean exactly about the minimised windows? Can you provide screenshots?
