### ISSUE TITLE
Prevent duplicate app launches

### ISSUE THREAD

**Issue by alexanderzhirov** [neagix/idesk#8]
Is it possible to prohibit re-launching an application if it has already been launched? So that when you click on the icon, a duplicate application does not start?

**Comment by RamKromberg** [comment]
Preventing app re-launch without implementing the locking in the app itself is susceptible to race conditions. Nevertheless, it can be done with a script that greps against lsof and sets up a dotfile lock: https://www.baeldung.com/linux/bash-ensure-instance-running

**Comment by neagix** [comment]
This would be out of scope for idesk.
